pyDjango/ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    #/blog/
    path('', views.PostLV.as_view(), name='index'),
    #/blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),
    #/blog/post/django-example
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    #/blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    #/blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    #/blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    #/blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    #/blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    #/blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),#TemplateView를 상속받아 정의
    #/blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),#ListView를 상속받아 정의
    #/blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
]

pyDjango/ch99/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView

from mysite.views import UserCreateView, UserCreateDoneTV #register를 처리하는 뷰 임포트


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pyDjango/ch99/blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = 'post' #테이블 단수 별칭
        verbose_name_plural = 'posts' #테이블 복수 별칭
        db_table = 'blog_posts' #디폴트는 앱명_모델명(blog_post)
        ordering = ('-modify_dt',) #출력 시 modify_dt를 기준으로 내림차순 정렬
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))
    
    def get_previous(self):
        return self.get_previous_by_modify_dt()#장고의 내장함수, modify_dt()를 기준으로 최신포스트를 반환

    def get_next(self):
        return self.get_next_by_modify_dt()

pyDjango/ch99/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

pyDjango/ch99/blog/views.py
#클래스형 제네릭 뷰 임포트
from django.views.generic import ListView, DetailView,TemplateView, FormView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.conf import settings

#테이블 조회를 위해 post모델 클래스를임포트
from blog.models import Post

#검색 기능을 위해 forms에 만들어둔 form추가, Q클래스 임포트
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render


# ListView
class PostLV(ListView): 
    model = Post #post테이블 가져옴
    template_name = 'blog/post_all.html' #템플릿 파일을 지정한다. 지정하지 않을 경우 blog/post_list.html로 설정됨
    context_object_name = 'posts' #템플릿 파일에 넘겨주는 객체명을 posts로 변경, 변경해도 기존의 'object_list를 사용할 수 있음
    paginate_by = 4 #한 페이지에 보여주는 객체리스트의 숫자는 2로 설정. 장고가 페이징 기능을 제공함.

# DetailView
class PostDV(DetailView): 
    # DetailView 제네릭 뷰를 상속받아 PostDV 클래스형 뷰를 정의함. 
    # DetailView 제네릭 뷰는 테이블로부터 특정 객체를 가져와 그 객체의 상세 정보를 출력. 
    # 테이블에서 특정 객체를 조회하기 위한 키는 기본 키 대신 slug속성을 사용하고 있음. 
    # 이 slug파라미터는 URLconf에서 추출해 뷰로 넘겨줌.
    model = Post

    #템플릿에 넘겨줄 변수를 정의함.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}" #고유한 id를 만들어주기 위함. 
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}" #ex)http://127.0.0.1:8000/blog/post/99
        context['disqus_title'] = f"{self.object.slug}"
        return context


# ArchiveView
class PostAV(ArchiveIndexView):
    model = Post # 대상 테이블
    date_field = 'modify_dt' #기준이 되는 날짜 필드는 'modify_dt'를 사용함
    make_object_list = True #해당 연도에 해당하는 객체의 리스트를 만들어서 템플릿에 넘겨줍니다. 템플릿 파일에서 object_list 컨텍스트 변수를 사용할 수 있다.

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

#FormView : GET 요청인 경우 폼을 화면에 보여줌. POST 요청의 경우 데이터의 유효성 검사를 한 후, 데이터가 유효하면 form_valid()함수를 실행한 후 리다이렉트 시킴.
#(하지만, 여기에서는 HttpResponse객체를 반환)
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | Q(description__icontains=searchWord) | Q(content__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

pyDjango/ch99/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %} post_all.html {% endblock %}

{% block content %}
<h1>Blog Tab</h1>
    <br>

    {% for post in posts %} <!-- posts객체는 PostLV 클래스 뷰에서 넘겨주는 컨택스트 변수로서, Post 객체 리스트가 담겨 있음. posts 대신에 object_list 컨택스트 변수를 사용해도 됨.-->
        <h3><a href='{% url "blog:post_detail" post.slug %}'>{{ post.title }}</a></h3> <!-- {{ post.get_absolute_url }} 이것과 동임-->
        {{ post.modify_dt|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    {% endfor %}

    <br>

    <div>
        <span>
            {% if page_obj.has_previous %} <!-- 만일 이전 페이지가 있다면,-->
                <a href = "?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} <!-- 현재페이지 변호 of 총 페이지 수-->
        
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

pyDjango/ch99/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
<h1>Post Archives until {% now "N d, Y" %}</h1>
    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
             <a href = "{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:'Y' }}</a></li>
        {% endfor %}
    </ul>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

pyDjango/ch99/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
    <h1>Post Archives for {{ day|date:"N d, Y" }}</h1> <!-- year컨텍스트 변수는 해당 연도에 대한 datetime.date타입의 객체-->

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

pyDjango/ch99/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
    <h1>Post Archives for {{ month|date:"N, Y" }}</h1> <!-- year컨텍스트 변수는 해당 연도에 대한 datetime.date타입의 객체-->

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

pyDjango/ch99/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
    <h1>Post Archives for {{ year|date:"Y" }}</h1> <!-- year컨텍스트 변수는 해당 연도에 대한 datetime.date타입의 객체-->

    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }} </a></li>
        {% endfor %}
    </ul>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

pyDjango/ch99/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

<!-- {% block extra-style %}
<style>
    /* .post-body{
        width: 80%
        margin: auto;
        font-family: "Lucida Grande", Verdana, Arial, sans-serif;
        font-size: 16px;
    } */
</style>
{% endblock extra-style %} -->

{% block content %}
<div class="post-body">
<h2>{{ object.title }}</h2>
    <p>
        {% if object.get_previous %} <!-- get_previous 함수는 modify_dt 칼럼 기준으로 이전 객체를 반환. 즉, 변경 날짜가 현재보다 더 최신 객체가 있는지 확인.-->
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post"> <!-- object.get_previous.get_absolute_url 함수는 이전 객체를 지칭하는 url패턴을 반환-->
            {{ object.get_previous }}
        </a>
        {% endif %}

        {% if object.get_next %}
        | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
          {{ object.get_next }}
        </a>
        {% endif %}
    </p>

    <p>{{ object.modify_dt|date:"j F Y" }}</p> <!-- 장고 템플릿 필터 date, time 포맷문자 -->
    <br>

    <div>
        {{ object.content|linebreaks }}
    </div>

    <br>
    <div>
        <b>TAGS</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %} 
        {% get_tags_for_object object as "tags" %}
        {% for tag in tags %}
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
        &emsp;
        <a href="{% url 'blog:tag_cloud' %}"><span class="btn btn-info btn-sm">TagCloud</span></a>
    </div>

    <br>
    <div id="disqus_thread"></div>
</div>
{% endblock %}

{% block extra-script %}
<script>


(function() {
    var d = document, s = d.createElement('script');
    s.src = 'https://{{ disqus_short }}.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            
{% endblock %}

pyDjango/ch99/blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
<h1>Post Search</h1>
<br>

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }} <!-- form을 테이블 형식으로 표시, 여기서 form은 views에서 넘겨준 PostSearchForm 객체임-->
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>

<br/><br/>

{% if object_list %}
    {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_date|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    {% endfor %}
{% elif search_term %}<!-- 검색란이 공란인지 확인-->
    <b><i>Search Word({{ search_term }}) Not Found</i></b>
{% endif %}
{% endblock %}