pyDjango/ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    #/blog/
    path('', views.PostLV.as_view(), name='index'),
    #/blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),
    #/blog/post/django-example
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    #/blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    #/blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    #/blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    #/blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    #/blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    #/blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),#TemplateView를 상속받아 정의
    #/blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),#ListView를 상속받아 정의
    #/blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
]

pyDjango/ch99/bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkLV, BookmarkDV

app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

pyDjango/ch99/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView

from mysite.views import UserCreateView, UserCreateDoneTV #register를 처리하는 뷰 임포트


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pyDjango/ch99/bookmark/models.py
from django.db import models

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    memo = models.TextField('MEMO', blank=True)

    def __str__(self):
        return self.title

pyDjango/ch99/bookmark/views.py
from django.views.generic import ListView, DetailView #클래스형 제네릭 뷰 임포트하기위해 ListView, DetailView클래스 임포트
from bookmark.models import Bookmark #테이블 조회를 위해 모델클래스 임포트

class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark

pyDjango/ch99/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %} bookmark_detail.html {% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>
<br>
<ul>
    <li>사이트 바로가기 : <a href="{{ object.url }}"  target="_blank">{{ object.url }}</a></li>
    <li>개발일지 : <a href="https://velog.io/@mongle/series/SpartaCoingClub8%EA%B8%B0%EC%8A%A4%ED%8C%8C%EB%A5%B4%ED%83%80-%EC%BD%94%EB%94%A9%ED%81%B4%EB%9F%BD"  target="_blank">개발일지</a></li>
</ul>
{% endblock %}

pyDjango/ch99/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %} bookmark_list.html {% endblock %}

{% block content %}
<h1>WebProjects</h1>
<br>
<ul>
    {% for bookmark in object_list %}
        <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

   