pyDjango/ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    #/blog/
    path('', views.PostLV.as_view(), name='index'),
    #/blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),
    #/blog/post/django-example
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    #/blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    #/blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    #/blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    #/blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    #/blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    #/blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),#TemplateView를 상속받아 정의
    #/blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),#ListView를 상속받아 정의
    #/blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
]

pyDjango/ch99/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView

from mysite.views import UserCreateView, UserCreateDoneTV #register를 처리하는 뷰 임포트


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pyDjango/ch99/photo/urls.py
from django.urls import path
from photo import views

app_name='photo'
urlpatterns = [
    #/photo/
    path('', views.AlbumLV.as_view(), name='index'),
    #/photo/album/ (same as /photo/)
    path('album', views.AlbumLV.as_view(), name='album_list'),
    #/photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),
    #/photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

]

pyDjango/ch99/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title%} Django Web Project {% endblock %}</title>

    <!-- css bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- js bootstrap-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    <style>
        
        .box{
            margin-top: 20px;
            padding-left: 40px;
            padding-right: 40px;
            margin-bottom: 20px;
            
        }

        
    </style>
    {% block extra-style %}{% endblock %}
    {% block extra-script %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
          aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a href="{% url 'home' %}"><span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Jeongseo-Django Web Project</span></a>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item mx-1">
                <a class="nav-link" href="# ">소개</a>
              </li>
            
            <li class="nav-item mx-1">
              <a class="nav-link" href="{% url 'blog:index' %}">게시판</a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'blog:search' %}">검색</a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'blog:post_archive' %}">모아보기</a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'photo:index' %}">사진첩</a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="https://github.com/Jeongseo21/django_project/tree/master/pyDjango/ch99" target="_blank">소스코드</a>
            </li>
            
            
            
            
            
            <!-- <li class="nav-item mx-1 dropdown">
                <a class="nav-link dropdown-toggle" href="#"
                    data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                </div>
            </li> dropdown 기능 삭제-->
            
          </ul>
          <ul class="navbar-nav" style="margin-right: 70px;">
            <li class="nav-item dropdown mx-1">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;Anonymous&ensp;
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </li>
        </ul>
        </div>
      </nav>  
        </div>
    </nav>

    <div class="box">
        {% block content %}{% endblock %}
    </div>


    {% block footer %}{% endblock %}

</body>
</html>

pyDjango/ch99/templates/home.html
<!-- base.html 템플릿 상속받음-->
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style>
    .home-image{
        background-image: url("{% static 'img/pizza.png' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: auto;
        /* background-color: #D6D6D6; */
        height: 700px;
        /* border-top: 10px solid;
        border-bottom: 10px solid; */
        padding: 20px 0 0 20px;
    }
    .title{
        color: #c80;
        font-weight: bold;
    }
    .powered{
        position: relative;
        top: 77%;
        color: dimgray;
        font-style: italic;
    }
</style>
{% endblock %}

{% block content %}
<div class="home-image">
    <h2 class="title">Jeongseo-Django Web Project</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i>먹방짤저장소 upgrade version</h4>
</div>


<!-- <div class="row text-center">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p>
            This is Bookmark App
            Thank you.
        </p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p>
            This is Blog App
            Thank you.
        </p>
    </div>
</div> -->
{% endblock %}

{% block footer %}
<footer class="fixed-bottom bg-secondary">
    <div class="text-white fornt-italic text-right mr-5">Copyright &copy; 2020 DjangoProject by HanJeonseo</div>
</footer>
{% endblock %}